<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('users')->insert([
            [
                'id' => '1',
                'first_name' => 'HICHAM',
                'last_name' => 'EL MESSIOUI',
                'email' => 'superadmin@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'EA88479',
                'phone'=> '0648813816',
                'birthday'=> '1990-01-01',
                'date_contract'=> '2021-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '0',
            ],  
            [
                'id' => '2',
                'first_name' => 'Ezzahra',
                'last_name' => 'ELMOURABIT',
                'email' => 'manager1@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'EE88409',
                'phone'=> '0697726285',
                'birthday'=> '1990-01-01',
                'date_contract'=> '2021-11-08',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '10000',
            ],
            [
                'id' => '3',
                'first_name' => 'Chris Axel',
                'last_name' => 'Bélanger',
                'email' => 'manager2@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'E88479',
                'phone'=> '0602806937',
                'birthday'=> '1990-01-01',
                'date_contract'=> '2021-04-02',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '10000',
            ],
            [
                'id' => '4',
                'first_name' => 'Hanane',
                'last_name' => 'Hdimane',
                'email' => 'manager4@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'EE88479',
                'phone'=> '0648813816',
                'birthday'=> '1990-01-01',
                'date_contract'=> '2021-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'h2f',
                'base_salary'=> '10000',
            ],
            [
                'id' => '5',
                'first_name' => 'Amine',
                'last_name' => 'Manager',
                'email' => 'manager3@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'EE8849',
                'phone'=> '0648813816',
                'birthday'=> '1990-01-01',
                'date_contract'=> '2021-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '10000',
            ], 
           [
                'id' => '6',
                'first_name' => 'Mahdi',
                'last_name' => 'IBN ELARYF',
                'email' => 'mehdi.lhphone@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'EE88479',
                'phone'=> '0659656100',
                'birthday'=> '1990-01-01',
                'date_contract'=> '2021-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'h2f',
                'base_salary'=> '6000',
            ],
            [
                'id' => '7',
                'first_name' => 'Hafssa',
                'last_name' => 'Ghalbane',
                'email' => 'hafssa.ghalbane@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'EE88479',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '6000',
            ], 
            [
                'id' => '8',
                'first_name' => 'Agent',
                'last_name' => '01',
                'email' => 'agent1@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent1',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '3500',
            ],
            [
                'id' => '9',
                'first_name' => 'Agent',
                'last_name' => '2',
                'email' => 'agent2@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent2',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '4000',
            ],
            [
                'id' => '10',
                'first_name' => 'Agent',
                'last_name' => '3',
                'email' => 'agent3@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent3',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '4500',
            ],
            [
                'id' => '11',
                'first_name' => 'Agent',
                'last_name' => '4',
                'email' => 'agent4@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent4',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '5000',
            ],
            [
                'id' => '12',
                'first_name' => 'Agent',
                'last_name' => '5',
                'email' => 'agent5@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent5',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '5500',
            ],
            [
                'id' => '13',
                'first_name' => 'Agent',
                'last_name' => '6',
                'email' => 'agent6@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent6',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '6000',
            ],
            [
                'id' => '14',
                'first_name' => 'Agent',
                'last_name' => '7',
                'email' => 'agent7@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent7',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '6500',
            ],
            [
                'id' => '16',
                'first_name' => 'Agent',
                'last_name' => '8',
                'email' => 'agent8@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent8',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '4000',
            ],
            [
                'id' => '17',
                'first_name' => 'Agent',
                'last_name' => '9',
                'email' => 'agent9@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent9',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '3500',
            ],
            [
                'id' => '18',
                'first_name' => 'Agent',
                'last_name' => '10',
                'email' => 'agent10@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent10',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '3500',
            ],
            [
                'id' => '19',
                'first_name' => 'Agent',
                'last_name' => '11',
                'email' => 'agent11@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent11',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '3500',
            ],
            [
                'id' => '20',
                'first_name' => 'Agent',
                'last_name' => '12',
                'email' => 'agent12@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent12',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '4500',
            ],
            [
                'id' => '21',
                'first_name' => 'Agent',
                'last_name' => '13',
                'email' => 'agent13@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent13',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '5500',
            ],
            [
                'id' => '22',
                'first_name' => 'Agent',
                'last_name' => '14',
                'email' => 'agent14@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent14',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '6500',
            ],
            [
                'id' => '23',
                'first_name' => 'Agent',
                'last_name' => '15',
                'email' => 'agent15@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent15',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '5500',
            ],
            [
                'id' => '24',
                'first_name' => 'Agent',
                'last_name' => '16',
                'email' => 'agent16@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent16',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '3500',
            ],
            [
                'id' => '26',
                'first_name' => 'Agent',
                'last_name' => '17',
                'email' => 'agent17@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent17',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '4500',
            ],
            [
                'id' => '27',
                'first_name' => 'Agent',
                'last_name' => '18',
                'email' => 'agent18@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent18',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '3500',
            ],
            [
                'id' => '28',
                'first_name' => 'Agent',
                'last_name' => '19',
                'email' => 'agent19@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent19',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '5000',
            ],
            [
                'id' => '30',
                'first_name' => 'Agent',
                'last_name' => '20',
                'email' => 'agent20@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent20',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '4500',
            ],
            [
                'id' => '31',
                'first_name' => 'Agent',
                'last_name' => '21',
                'email' => 'agent21@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agent21',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'lh',
                'base_salary'=> '5500',
            ],
            [
                'id' => '32',
                'first_name' => 'Agent',
                'last_name' => 'H2F1',
                'email' => 'agentH2F1@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agentH2F1',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'h2f',
                'base_salary'=> '5500',
            ],
            [
                'id' => '33',
                'first_name' => 'Agent',
                'last_name' => 'H2F2',
                'email' => 'agentH2F2@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agentH2F2',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'h2f',
                'base_salary'=> '5500',
            ],
            [
                'id' => '34',
                'first_name' => 'Agent',
                'last_name' => 'H2F3',
                'email' => 'agentH2F3@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agentH2F3',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'h2f',
                'base_salary'=> '4000',
            ],
            [
                'id' => '35',
                'first_name' => 'Agent',
                'last_name' => 'H2F4',
                'email' => 'agentH2F4@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agentH2F4',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'h2f',
                'base_salary'=> '2500',
            ],
            [
                'id' => '36',
                'first_name' => 'Agent',
                'last_name' => 'H2F5',
                'email' => 'agentH2F5@gmail.com',
                'password' => bcrypt('password'),
                'id_card'=> 'agentH2F5',
                'phone'=> '0648813816',
                'birthday'=> '2000-05-08',
                'date_contract'=> '2023-05-17',
                'type_contract'=> 'CDD',
                'company'=> 'h2f',
                'base_salary'=> '5500',
            ], 

        ]); 
    }
}

